spring.application.name=task-manager-api

spring.datasource.url=jdbc:postgresql://localhost:5432/spring-task-manager
spring.datasource.username=postgres
spring.datasource.password=Ebaharam8!

spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework.security=debug
